# {{ ansible_managed }}
master:
 image:  {{docker_repo}}{{master_image}}:{{master_version}}
 volumes:
  - /var/jenkins_home:/var/jenkins_home
 ports:
  - "{{masterPort}}:8080"
 environment:
 - JAVA_OPTS=-Duser.timezone={{timezone}}

nginx:
 image:  {{docker_repo}}{{nginx_image}}:{{nginx_version}}

